import { CaptionPreset, CaptionStyle } from './types';

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'it', name: 'Italian' },
  { code: 'ja', name: 'Japanese' },
  { code: 'ko', name: 'Korean' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ru', name: 'Russian' },
  { code: 'zh', name: 'Chinese' },
];

export const ASPECT_RATIOS = [
  { ratio: '16:9', name: 'YouTube / Landscape', description: 'Standard video, Facebook, Twitter' },
  { ratio: '9:16', name: 'Instagram Reels / TikTok', description: 'Vertical video, Stories' },
  { ratio: '1:1', name: 'Instagram Feed / Square', description: 'Square format, LinkedIn' },
  { ratio: '4:5', name: 'Instagram Portrait', description: 'Portrait post' },
];

export const FONT_FAMILIES = [
  { name: 'Arial', value: 'Arial, sans-serif' },
  { name: 'Arial Black', value: '"Arial Black", sans-serif' },
  { name: 'Impact', value: 'Impact, sans-serif' },
  { name: 'Verdana', value: 'Verdana, sans-serif' },
  { name: 'Tahoma', value: 'Tahoma, sans-serif' },
  { name: 'Times New Roman', value: '"Times New Roman", serif' },
  { name: 'Georgia', value: 'Georgia, serif' },
  { name: 'Courier New', value: '"Courier New", monospace' },
  { name: 'Comic Sans MS', value: '"Comic Sans MS", cursive' },
  { name: 'Trebuchet MS', value: '"Trebuchet MS", sans-serif' },
  // Instagram Reels & Social Media Fonts
  { name: 'Montserrat', value: 'Montserrat, sans-serif' },
  { name: 'Poppins', value: 'Poppins, sans-serif' },
  { name: 'Bebas Neue', value: '"Bebas Neue", sans-serif' },
  { name: 'Anton', value: 'Anton, sans-serif' },
  { name: 'Oswald', value: 'Oswald, sans-serif' },
  { name: 'Raleway', value: 'Raleway, sans-serif' },
];

export const DEFAULT_STYLE: CaptionStyle = {
  fontSize: 32,
  primaryColor: '#FFFFFF',
  activeColor: '#FFFF00',
  outlineColor: '#000000',
  outlineWidth: 2,
  fontWeight: 700,
  backgroundColor: '#000000',
  backgroundOpacity: 0.5,
  position: { x: 50, y: 80 },
  fontFamily: 'Arial, sans-serif',
  textAlign: 'center',
  letterSpacing: 0,
  lineHeight: 1.2,
  borderRadius: 8,
};

export const CAPTION_PRESETS: CaptionPreset[] = [
  {
    name: 'Minimalist',
    fontSize: 28,
    primaryColor: '#FFFFFF',
    activeColor: '#FFFFFF', // Same as primary to disable effect
    outlineWidth: 0,
    fontWeight: 500,
    backgroundOpacity: 0,
    fontFamily: 'Arial, sans-serif',
    letterSpacing: 0.5,
    lineHeight: 1.3,
    borderRadius: 0,
  },
  {
    name: 'Classic',
    fontSize: 32,
    primaryColor: '#FFFFFF',
    activeColor: '#FFFF00',
    outlineColor: '#000000',
    outlineWidth: 2,
    fontWeight: 700,
    backgroundOpacity: 0.5,
    fontFamily: 'Arial, sans-serif',
    letterSpacing: 0,
    lineHeight: 1.2,
    borderRadius: 8,
  },
  {
    name: 'Impact',
    fontSize: 48,
    primaryColor: '#FFFF00',
    activeColor: '#FFFFFF',
    outlineColor: '#000000',
    outlineWidth: 3,
    fontWeight: 900,
    backgroundOpacity: 0,
    fontFamily: 'Impact, sans-serif',
    letterSpacing: 1,
    lineHeight: 1.1,
    borderRadius: 0,
  },
  {
    name: 'Clean',
    fontSize: 30,
    primaryColor: '#000000',
    activeColor: '#4F46E5', // Indigo-600
    outlineWidth: 0,
    fontWeight: 600,
    backgroundColor: '#FFFFFF',
    backgroundOpacity: 0.8,
    fontFamily: 'Verdana, sans-serif',
    letterSpacing: 0,
    lineHeight: 1.4,
    borderRadius: 12,
  },
  {
    name: 'Neon',
    primaryColor: '#39FF14',
    activeColor: '#F0F9FF',
    outlineColor: '#000000',
    outlineWidth: 1,
    fontWeight: 700,
    backgroundOpacity: 0,
    fontFamily: '"Arial Black", sans-serif',
    letterSpacing: 1.5,
    lineHeight: 1.2,
    borderRadius: 0,
  },
  {
    name: 'Karaoke',
    fontSize: 42,
    primaryColor: '#E5E7EB',
    activeColor: '#F87171',
    outlineColor: '#000000',
    outlineWidth: 3,
    fontWeight: 900,
    backgroundOpacity: 0.2,
    fontFamily: '"Arial Black", sans-serif',
    letterSpacing: 0.5,
    lineHeight: 1.1,
    borderRadius: 16,
  },
  {
    name: 'Instagram Reels',
    fontSize: 40,
    primaryColor: '#FFFFFF',
    activeColor: '#FF0080', // Instagram pink
    outlineColor: '#000000',
    outlineWidth: 2.5,
    fontWeight: 900,
    backgroundColor: '#000000',
    backgroundOpacity: 0.15,
    fontFamily: 'Montserrat, sans-serif',
    letterSpacing: 0.8,
    lineHeight: 1.15,
    borderRadius: 10,
  },
];